### ISSUE TITLE
Rename CSVs

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/aggregator#3] opened 2016-09-26 10:06 UTC
CSV files should use English singular, not plural, i.e.:

* [x] "entries.csv" -> "entry.csv"
* [x] "places.csv" -> "place.csv"
* [x] "risks.csv" -> "risk.csv"

**Comment by zelima** [comment] 2016-09-27 14:45
Please see: https://github.com/cybergreen-net/aggregator/issues/4#issuecomment-249885722 
This becomes duplicate of #4

**Comment by GregoryRhysEvans** [comment] 2016-09-27 15:50
@zelima They aren't duplicates. This is the issue for renaming csvs, tables and references to them in the code to their singular names (so all "entries" should become "entry")

The other one is the issue for the problem of .csv extensions on the offload to S3

**Comment by zelima** [comment] 2016-09-28 15:08
All table names that mention entries are changed with count. all table names that mention place changed to country.

**Comment by aaronkaplan** [comment] 2016-09-28 15:12
fantastic! thx.

**Comment by aaronkaplan** [comment] 2016-09-28 16:10
Question: these changes are not live yet? Because actually s/place/country will also apply to the code (the URL will be .../country/ instead of /place) etc.
Is all of that fixed?

PS: I think @zelima you commented this against the wrong issue maybe.

**Comment by zelima** [comment] 2016-09-29 13:47
Links now point to country instead of place.
Closing

**Closed by zelima** 2016-09-29 13:47 UTC
